# 1. Import and Install Dependencies

In [1]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp
import joblib
import pickle

# 2. Keypoints using MP Holistic

In [2]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

In [3]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [4]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 

In [21]:
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

# 3. Extract Keypoint Values

In [5]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([pose, face, lh, rh])

# 4. Setup Folders for Collection

In [6]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('real_time_data') 

# Actions that we try to detect
actions = np.array(['healthy','hello','iloveyou','thanks'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30

In [7]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
           os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

# 5. Collect Keypoint Values for Training and Testing

In [8]:
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)
#                 print(results)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(2000)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [23]:
cap.release()
cv2.destroyAllWindows()

# 6. Preprocess Data and Create Labels and Features

In [9]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [10]:
label_map = {label:num for num, label in enumerate(actions)}

In [11]:
label_map

{'healthy': 0, 'hello': 1, 'iloveyou': 2, 'thanks': 3}

In [12]:
sequences, labels = [], []
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [13]:
X = np.array(sequences)

In [14]:
y = to_categorical(labels).astype(int)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

# 7. Build and Train LSTM Neural Network

In [51]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [52]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [53]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

In [54]:
res = [.7, 0.2, 0.1]

In [55]:
actions[np.argmax(res)]

'healthy'

In [56]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [57]:
model.fit(X_train, y_train, epochs=2000, callbacks=[tb_callback])

Epoch 1/2000
4/4 [==============================] - 3s 134ms/step - loss: 9.1761 - categorical_accuracy: 0.3070
Epoch 2/2000
4/4 [==============================] - 1s 132ms/step - loss: 13.4150 - categorical_accuracy: 0.2544
Epoch 3/2000
4/4 [==============================] - 0s 127ms/step - loss: 11.1494 - categorical_accuracy: 0.1930
Epoch 4/2000
4/4 [==============================] - 1s 129ms/step - loss: 13.8711 - categorical_accuracy: 0.2456
Epoch 5/2000
4/4 [==============================] - 0s 123ms/step - loss: 6.4542 - categorical_accuracy: 0.2544
Epoch 6/2000
4/4 [==============================] - 0s 125ms/step - loss: 10.4330 - categorical_accuracy: 0.2105
Epoch 7/2000
4/4 [==============================] - 0s 124ms/step - loss: 10.0331 - categorical_accuracy: 0.2982
Epoch 8/2000
4/4 [==============================] - 0s 126ms/step - loss: 6.9956 - categorical_accuracy: 0.2193
Epoch 9/2000
4/4 [==============================] - 1s 144ms/step - loss: 6.2596 - categorical_accu

4/4 [==============================] - 0s 116ms/step - loss: 0.9440 - categorical_accuracy: 0.5526
Epoch 74/2000
4/4 [==============================] - 1s 132ms/step - loss: 0.9208 - categorical_accuracy: 0.5614
Epoch 75/2000
4/4 [==============================] - 0s 121ms/step - loss: 0.8856 - categorical_accuracy: 0.6140
Epoch 76/2000
4/4 [==============================] - 1s 132ms/step - loss: 0.9837 - categorical_accuracy: 0.5175
Epoch 77/2000
4/4 [==============================] - 1s 135ms/step - loss: 0.9706 - categorical_accuracy: 0.5614
Epoch 78/2000
4/4 [==============================] - 1s 128ms/step - loss: 0.9584 - categorical_accuracy: 0.5614
Epoch 79/2000
4/4 [==============================] - 1s 133ms/step - loss: 0.9383 - categorical_accuracy: 0.6053
Epoch 80/2000
4/4 [==============================] - 1s 133ms/step - loss: 0.9580 - categorical_accuracy: 0.5789
Epoch 81/2000
4/4 [==============================] - 0s 123ms/step - loss: 0.9478 - categorical_accuracy: 0.54

4/4 [==============================] - 1s 130ms/step - loss: 0.7544 - categorical_accuracy: 0.6754
Epoch 146/2000
4/4 [==============================] - 0s 124ms/step - loss: 0.6909 - categorical_accuracy: 0.6754
Epoch 147/2000
4/4 [==============================] - 1s 140ms/step - loss: 0.6649 - categorical_accuracy: 0.6842
Epoch 148/2000
4/4 [==============================] - 1s 138ms/step - loss: 1.3670 - categorical_accuracy: 0.5175
Epoch 149/2000
4/4 [==============================] - 1s 136ms/step - loss: 1.2067 - categorical_accuracy: 0.4737
Epoch 150/2000
4/4 [==============================] - 1s 136ms/step - loss: 0.9913 - categorical_accuracy: 0.5526
Epoch 151/2000
4/4 [==============================] - 1s 127ms/step - loss: 0.9876 - categorical_accuracy: 0.5351
Epoch 152/2000
4/4 [==============================] - 1s 129ms/step - loss: 0.8873 - categorical_accuracy: 0.5789
Epoch 153/2000
4/4 [==============================] - 1s 141ms/step - loss: 0.8827 - categorical_accura

Epoch 217/2000
4/4 [==============================] - 1s 132ms/step - loss: 0.6310 - categorical_accuracy: 0.6842
Epoch 218/2000
4/4 [==============================] - 1s 132ms/step - loss: 0.6246 - categorical_accuracy: 0.6930
Epoch 219/2000
4/4 [==============================] - 1s 138ms/step - loss: 0.6399 - categorical_accuracy: 0.6754
Epoch 220/2000
4/4 [==============================] - 1s 135ms/step - loss: 0.6378 - categorical_accuracy: 0.6842
Epoch 221/2000
4/4 [==============================] - 1s 135ms/step - loss: 0.6303 - categorical_accuracy: 0.6754
Epoch 222/2000
4/4 [==============================] - 0s 123ms/step - loss: 0.6212 - categorical_accuracy: 0.6579
Epoch 223/2000
4/4 [==============================] - 1s 146ms/step - loss: 0.6662 - categorical_accuracy: 0.6930
Epoch 224/2000
4/4 [==============================] - 0s 118ms/step - loss: 0.8010 - categorical_accuracy: 0.6404
Epoch 225/2000
4/4 [==============================] - 1s 136ms/step - loss: 0.9078 - cat

4/4 [==============================] - 1s 138ms/step - loss: 0.5735 - categorical_accuracy: 0.7368
Epoch 289/2000
4/4 [==============================] - 1s 132ms/step - loss: 0.5911 - categorical_accuracy: 0.7368
Epoch 290/2000
4/4 [==============================] - 0s 120ms/step - loss: 0.5775 - categorical_accuracy: 0.7105
Epoch 291/2000
4/4 [==============================] - 0s 122ms/step - loss: 0.5611 - categorical_accuracy: 0.7544
Epoch 292/2000
4/4 [==============================] - 0s 121ms/step - loss: 0.5397 - categorical_accuracy: 0.7719
Epoch 293/2000
4/4 [==============================] - 1s 149ms/step - loss: 0.5320 - categorical_accuracy: 0.7368
Epoch 294/2000
4/4 [==============================] - 1s 140ms/step - loss: 0.5031 - categorical_accuracy: 0.7456
Epoch 295/2000
4/4 [==============================] - 1s 123ms/step - loss: 0.5252 - categorical_accuracy: 0.7456
Epoch 296/2000
4/4 [==============================] - 0s 121ms/step - loss: 0.4750 - categorical_accura

Epoch 360/2000
4/4 [==============================] - 0s 118ms/step - loss: 0.5232 - categorical_accuracy: 0.7281
Epoch 361/2000
4/4 [==============================] - 0s 128ms/step - loss: 0.5589 - categorical_accuracy: 0.7456
Epoch 362/2000
4/4 [==============================] - 1s 136ms/step - loss: 0.7769 - categorical_accuracy: 0.6579
Epoch 363/2000
4/4 [==============================] - 1s 133ms/step - loss: 0.7271 - categorical_accuracy: 0.6667
Epoch 364/2000
4/4 [==============================] - 1s 131ms/step - loss: 0.6536 - categorical_accuracy: 0.7018
Epoch 365/2000
4/4 [==============================] - 0s 120ms/step - loss: 0.6043 - categorical_accuracy: 0.6842
Epoch 366/2000
4/4 [==============================] - 0s 122ms/step - loss: 0.6616 - categorical_accuracy: 0.6754
Epoch 367/2000
4/4 [==============================] - 1s 136ms/step - loss: 0.5768 - categorical_accuracy: 0.7281
Epoch 368/2000
4/4 [==============================] - 1s 128ms/step - loss: 0.6100 - cat

4/4 [==============================] - 1s 133ms/step - loss: 0.4657 - categorical_accuracy: 0.7544
Epoch 432/2000
4/4 [==============================] - 1s 133ms/step - loss: 0.5651 - categorical_accuracy: 0.7368
Epoch 433/2000
4/4 [==============================] - 1s 129ms/step - loss: 0.5297 - categorical_accuracy: 0.7281
Epoch 434/2000
4/4 [==============================] - 0s 121ms/step - loss: 0.6731 - categorical_accuracy: 0.6754
Epoch 435/2000
4/4 [==============================] - 1s 130ms/step - loss: 0.7572 - categorical_accuracy: 0.6316
Epoch 436/2000
4/4 [==============================] - 1s 141ms/step - loss: 0.7327 - categorical_accuracy: 0.6930
Epoch 437/2000
4/4 [==============================] - 0s 120ms/step - loss: 0.6682 - categorical_accuracy: 0.6930
Epoch 438/2000
4/4 [==============================] - 0s 119ms/step - loss: 0.6622 - categorical_accuracy: 0.6579
Epoch 439/2000
4/4 [==============================] - 1s 128ms/step - loss: 0.6418 - categorical_accura

Epoch 503/2000
4/4 [==============================] - 1s 139ms/step - loss: 0.3749 - categorical_accuracy: 0.8070
Epoch 504/2000
4/4 [==============================] - 0s 122ms/step - loss: 0.3379 - categorical_accuracy: 0.8333
Epoch 505/2000
4/4 [==============================] - 1s 129ms/step - loss: 0.3504 - categorical_accuracy: 0.8333
Epoch 506/2000
4/4 [==============================] - 0s 117ms/step - loss: 0.3247 - categorical_accuracy: 0.8333
Epoch 507/2000
4/4 [==============================] - 1s 138ms/step - loss: 0.3152 - categorical_accuracy: 0.8421
Epoch 508/2000
4/4 [==============================] - 1s 139ms/step - loss: 0.3146 - categorical_accuracy: 0.8684
Epoch 509/2000
4/4 [==============================] - 1s 131ms/step - loss: 0.2907 - categorical_accuracy: 0.8684
Epoch 510/2000
4/4 [==============================] - 1s 138ms/step - loss: 0.3031 - categorical_accuracy: 0.8158
Epoch 511/2000
4/4 [==============================] - 0s 119ms/step - loss: 0.3219 - cat

4/4 [==============================] - 1s 128ms/step - loss: 0.6345 - categorical_accuracy: 0.6842
Epoch 575/2000
4/4 [==============================] - 1s 133ms/step - loss: 0.5721 - categorical_accuracy: 0.7368
Epoch 576/2000
4/4 [==============================] - 0s 121ms/step - loss: 0.7046 - categorical_accuracy: 0.6754
Epoch 577/2000
4/4 [==============================] - 1s 136ms/step - loss: 0.5058 - categorical_accuracy: 0.7544
Epoch 578/2000
4/4 [==============================] - 1s 151ms/step - loss: 0.5128 - categorical_accuracy: 0.7368
Epoch 579/2000
4/4 [==============================] - 1s 132ms/step - loss: 0.4440 - categorical_accuracy: 0.7982
Epoch 580/2000
4/4 [==============================] - 1s 127ms/step - loss: 0.4184 - categorical_accuracy: 0.8070
Epoch 581/2000
4/4 [==============================] - 0s 117ms/step - loss: 0.4072 - categorical_accuracy: 0.8246
Epoch 582/2000
4/4 [==============================] - 1s 135ms/step - loss: 0.3738 - categorical_accura

KeyboardInterrupt: 

In [58]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_12 (LSTM)              (None, 30, 64)            442112    
                                                                 
 lstm_13 (LSTM)              (None, 30, 128)           98816     
                                                                 
 lstm_14 (LSTM)              (None, 64)                49408     
                                                                 
 dense_12 (Dense)            (None, 64)                4160      
                                                                 
 dense_13 (Dense)            (None, 32)                2080      
                                                                 
 dense_14 (Dense)            (None, 4)                 132       
                                                                 
Total params: 596,708
Trainable params: 596,708
Non-tr

# 8. Make Predictions

In [59]:
res = model.predict(X_test)

1/1 [==============================] - 0s 271ms/step


In [62]:
actions[np.argmax(res[0])]

'healthy'

In [63]:
actions[np.argmax(y_test[0])]

'thanks'

# 9. Save Weights

In [64]:
filename = "real_time_model.joblib"
joblib.dump(model, filename)

INFO:tensorflow:Assets written to: ram://2993aced-a726-4efb-83d8-3c601db093c0/assets


['real_time_model.joblib']

In [65]:
model.save('action.h5')

In [ ]:
model.load_weights('action.h5')

# 10. Evaluation using Confusion Matrix and Accuracy

In [66]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [67]:
yhat = model.predict(X_test)

1/1 [==============================] - 0s 49ms/step


In [68]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [69]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[1, 4],
        [1, 0]],

       [[4, 0],
        [2, 0]],

       [[4, 0],
        [1, 1]],

       [[4, 1],
        [1, 0]]], dtype=int64)

In [70]:
accuracy_score(ytrue, yhat)

0.16666666666666666

# 11. Test in Real Time

In [71]:
colors = [(245,117,16), (117,245,16), (16,117,245)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

In [72]:
plt.figure(figsize=(18,18))
plt.imshow(prob_viz(res, actions, image, colors))

TypeError: only size-1 arrays can be converted to Python scalars

<Figure size 1296x1296 with 0 Axes>

In [75]:
sequence.reverse()

In [76]:
len(sequence)

30

In [77]:
sequence.append('def')

In [78]:
sequence.reverse()

In [79]:
sequence[-30:]

[array([ 0.57346714,  0.74661976, -0.88560736, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57689357,  0.74561387, -0.86473691, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57739288,  0.742953  , -0.8346895 , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57805735,  0.73941422, -0.80412894, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57851088,  0.73825294, -0.81897688, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57889831,  0.73721337, -0.8415758 , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57961315,  0.73480147, -0.88926256, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57964939,  0.73347199, -0.85897124, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.57990515,  0.73245144, -0.85658753, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.5799551 ,  0.7293703 , -0.84974396, ...,  0.        ,
         0.        ,  0.  

In [90]:
# 1. New detection variables
sequence = []
sentence = []
threshold = 0.8

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 2000);
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1000);
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
#         print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
#         sequence.insert(0,keypoints)
#         sequence = sequence[:30]
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
#             print(actions[np.argmax(res)])
            
            
        #3. Viz logic
            if res[np.argmax(res)] > threshold: 
                if len(sentence) > 0: 
                    if actions[np.argmax(res)] != sentence[-1]:
                        sentence.append(actions[np.argmax(res)])
                else:
                    sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

1/1 [==============================] - 0s 37ms/step


IndexError: list index out of range

In [91]:
cap.release()
cv2.destroyAllWindows()

In [ ]:
res[np.argmax(res)] > threshold

In [ ]:
(num_sequences,30,1662)

In [ ]:
model.predict(np.expand_dims(X_test[0], axis=0))